name: Update LessonPlans README2.md

on:
  push:
    branches:
      - main
    paths:
      - LessonPlans/Grades1-3/**

jobs:
  update-readme2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run script to update README2.md
      run: python update_readme.py
      
    - name: List repository files
      run: ls -R
